In [1]:
import requests
from bs4 import BeautifulSoup
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np
import time
import os

from sentence_transformers import SentenceTransformer

## Utworzenie dataframe, scrapowanie danych

In [2]:
politicians_df = pd.DataFrame(columns=["politician", "utterance", "sejm_session", "date"])

In [3]:
gov_meetings_dict = {
    "2023-11-13": [1],
    "2023-11-14": [1],
    "2023-11-21": [1],
    "2023-11-22": [1],
    "2023-11-28": [1],
    "2023-11-29": [1],
    "2023-12-06": [1],
    "2023-12-07": [1],
    "2023-12-11": [1],
    "2023-12-12": [1],
    "2023-12-19": [1],
    "2023-12-20": [1],
    "2023-12-21": [1],
    "2024-01-16": [2],
    "2024-01-17": [2],
    "2024-01-18": [3],
    "2024-01-25": [4],
    "2024-01-26": [4],
    "2024-02-07": [5],
    "2024-02-08": [5],
    "2024-02-09": [5],
    "2024-02-21": [6],
    "2024-02-22": [6],
    "2024-03-06": [7],
    "2024-03-07": [7],
    "2024-03-08": [7],
    "2024-03-20": [8],
    "2024-03-21": [8],
    "2024-04-10": [9],
    "2024-04-11": [9],
    "2024-04-12": [9],
    "2024-04-24": [10],
    "2024-04-25": [10],
    "2024-04-26": [10],
    "2024-05-08": [11],
    "2024-05-09": [11],
    "2024-05-15": [11],
    "2024-05-22": [12],
    "2024-05-23": [12],
    "2024-06-12": [13],
    "2024-06-13": [13],
    "2024-06-14": [13],
    "2024-06-26": [14],
    "2024-06-27": [14],
    "2024-06-28": [14],
    "2024-07-11": [15],
    "2024-07-12": [15],
    "2024-07-23": [16],
    "2024-07-24": [16],
    "2024-07-25": [16],
    "2024-07-26": [16],
    "2024-09-11": [17],
    "2024-09-12": [17],
    "2024-09-13": [17],
    "2024-09-25": [18],
    "2024-09-26": [18],
    "2024-09-27": [18],
    "2024-10-01": [18],
    "2024-10-09": [19],
    "2024-10-10": [19],
    "2024-10-11": [19],
    "2024-10-16": [20],
    "2024-10-17": [20],
    "2024-10-18": [20],
    "2024-11-06": [21],
    "2024-11-07": [21],
    "2024-11-08": [21],
    "2024-11-19": [22],
    "2024-11-20": [22],
    "2024-11-21": [22],
    "2024-11-22": [22],
    "2024-11-27": [22],
    "2024-12-04": [23],
    "2024-12-05": [23],
    "2024-12-06": [24],
    "2024-12-18": [25],
    "2024-12-19": [25],
    "2024-12-20": [25],
    "2025-01-08": [26],
    "2025-01-09": [26],
    "2025-01-10": [26],
    "2025-01-22": [27],
    "2025-01-23": [27],
    "2025-01-24": [27]
}

## Przeiterowanie po każdej wypowiedzi każdego posiedzenia sejmowego (dzięki sejmowemu API) i zapisanie do jednego słownika, następnie wszystko do politicians_df

In [4]:
for name, key in gov_meetings_dict.items():
    for number in key:
        i = 1
        start_time = time.time()
        while True:
            url = f"https://api.sejm.gov.pl/sejm/term10/proceedings/{number}/{name}/transcripts/{i}"
            page = requests.get(url)
            soup = BeautifulSoup(page.text, 'html')
        
            element = soup.find('h2', class_='mowca')
            if element is not None:
                politician = element.text.strip()[:-1]
            else:
                print(f'Koniec wypowiedzi. Odnotowano: {i} przemówień')
                break
        
            utterance_elements = []
            for p in soup.find_all('p')[1:]:
                utterance_elements.append(p.text.strip())
            utterance = "".join(utterance_elements).strip()
        
            nowy_wiersz = pd.DataFrame({"politician": [politician], 
                                        "utterance": [utterance], 
                                        "sejm_session": [number], 
                                        "date": [name]})
            politicians_df = pd.concat([politicians_df, nowy_wiersz], ignore_index=True)
        
            i = i+1
        end_time = time.time()
        print(f'Czas posiedzenia nr {number} o dacie {name}: {end_time-start_time:.2f} sekundy \n')

Koniec wypowiedzi. Odnotowano: 43 przemówień
Czas posiedzenia nr 1 o dacie 2023-11-13: 26.31 sekundy

Koniec wypowiedzi. Odnotowano: 18 przemówień
Czas posiedzenia nr 1 o dacie 2023-11-14: 10.34 sekundy

Koniec wypowiedzi. Odnotowano: 33 przemówień
Czas posiedzenia nr 1 o dacie 2023-11-21: 18.40 sekundy

Koniec wypowiedzi. Odnotowano: 116 przemówień
Czas posiedzenia nr 1 o dacie 2023-11-22: 67.61 sekundy

Koniec wypowiedzi. Odnotowano: 191 przemówień
Czas posiedzenia nr 1 o dacie 2023-11-28: 105.04 sekundy

Koniec wypowiedzi. Odnotowano: 238 przemówień
Czas posiedzenia nr 1 o dacie 2023-11-29: 136.37 sekundy

Koniec wypowiedzi. Odnotowano: 156 przemówień
Czas posiedzenia nr 1 o dacie 2023-12-06: 85.88 sekundy

Koniec wypowiedzi. Odnotowano: 185 przemówień
Czas posiedzenia nr 1 o dacie 2023-12-07: 106.51 sekundy

Koniec wypowiedzi. Odnotowano: 161 przemówień
Czas posiedzenia nr 1 o dacie 2023-12-11: 89.25 sekundy

Koniec wypowiedzi. Odnotowano: 268 przemówień
Czas posiedzenia nr 1 o dacie 2023-12-12: 171.69 sekundy

Koniec wypowiedzi. Odnotowano: 163 przemówień
Czas posiedzenia nr 1 o dacie 2023-12-19: 103.36 sekundy

Koniec wypowiedzi. Odnotowano: 139 przemówień
Czas posiedzenia nr 1 o dacie 2023-12-20: 81.83 sekundy

Koniec wypowiedzi. Odnotowano: 217 przemówień
Czas posiedzenia nr 1 o dacie 2023-12-21: 120.58 sekundy

Koniec wypowiedzi. Odnotowano: 191 przemówień
Czas posiedzenia nr 2 o dacie 2024-01-16: 106.08 sekundy

Koniec wypowiedzi. Odnotowano: 158 przemówień
Czas posiedzenia nr 2 o dacie 2024-01-17: 92.77 sekundy

Koniec wypowiedzi. Odnotowano: 53 przemówień
Czas posiedzenia nr 3 o dacie 2024-01-18: 29.68 sekundy

Koniec wypowiedzi. Odnotowano: 172 przemówień
Czas posiedzenia nr 4 o dacie 2024-01-25: 96.38 sekundy

Koniec wypowiedzi. Odnotowano: 189 przemówień
Czas posiedzenia nr 4 o dacie 2024-01-26: 98.98 sekundy

Koniec wypowiedzi. Odnotowano: 169 przemówień
Czas posiedzenia nr 5 o dacie 2024-02-07: 88.36 sekundy

Koniec wypowiedzi. Odnotowano: 248 przemówień
Czas posiedzenia nr 5 o dacie 2024-02-08: 126.60 sekundy

Koniec wypowiedzi. Odnotowano: 99 przemówień
Czas posiedzenia nr 5 o dacie 2024-02-09: 52.94 sekundy

Koniec wypowiedzi. Odnotowano: 141 przemówień
Czas posiedzenia nr 6 o dacie 2024-02-21: 75.24 sekundy

Koniec wypowiedzi. Odnotowano: 204 przemówień
Czas posiedzenia nr 6 o dacie 2024-02-22: 106.37 sekundy

Koniec wypowiedzi. Odnotowano: 244 przemówień
Czas posiedzenia nr 7 o dacie 2024-03-06: 129.92 sekundy

Koniec wypowiedzi. Odnotowano: 245 przemówień
Czas posiedzenia nr 7 o dacie 2024-03-07: 128.48 sekundy

Koniec wypowiedzi. Odnotowano: 60 przemówień
Czas posiedzenia nr 7 o dacie 2024-03-08: 38.80 sekundy

Koniec wypowiedzi. Odnotowano: 202 przemówień
Czas posiedzenia nr 8 o dacie 2024-03-20: 104.58 sekundy

Koniec wypowiedzi. Odnotowano: 128 przemówień
Czas posiedzenia nr 8 o dacie 2024-03-21: 66.23 sekundy

Koniec wypowiedzi. Odnotowano: 165 przemówień
Czas posiedzenia nr 9 o dacie 2024-04-10: 86.44 sekundy

Koniec wypowiedzi. Odnotowano: 264 przemówień
Czas posiedzenia nr 9 o dacie 2024-04-11: 138.65 sekundy

Koniec wypowiedzi. Odnotowano: 129 przemówień
Czas posiedzenia nr 9 o dacie 2024-04-12: 66.67 sekundy

Koniec wypowiedzi. Odnotowano: 204 przemówień
Czas posiedzenia nr 10 o dacie 2024-04-24: 119.05 sekundy

Koniec wypowiedzi. Odnotowano: 137 przemówień
Czas posiedzenia nr 10 o dacie 2024-04-25: 89.20 sekundy

Koniec wypowiedzi. Odnotowano: 178 przemówień
Czas posiedzenia nr 10 o dacie 2024-04-26: 115.93 sekundy

Koniec wypowiedzi. Odnotowano: 207 przemówień
Czas posiedzenia nr 11 o dacie 2024-05-08: 129.76 sekundy

Koniec wypowiedzi. Odnotowano: 272 przemówień
Czas posiedzenia nr 11 o dacie 2024-05-09: 159.87 sekundy

Koniec wypowiedzi. Odnotowano: 240 przemówień
Czas posiedzenia nr 11 o dacie 2024-05-15: 147.57 sekundy

Koniec wypowiedzi. Odnotowano: 230 przemówień
Czas posiedzenia nr 12 o dacie 2024-05-22: 131.32 sekundy

Koniec wypowiedzi. Odnotowano: 174 przemówień
Czas posiedzenia nr 12 o dacie 2024-05-23: 106.57 sekundy

Koniec wypowiedzi. Odnotowano: 126 przemówień
Czas posiedzenia nr 13 o dacie 2024-06-12: 76.49 sekundy

Koniec wypowiedzi. Odnotowano: 243 przemówień
Czas posiedzenia nr 13 o dacie 2024-06-13: 142.38 sekundy

Koniec wypowiedzi. Odnotowano: 52 przemówień
Czas posiedzenia nr 13 o dacie 2024-06-14: 29.37 sekundy

Koniec wypowiedzi. Odnotowano: 1 przemówień
Czas posiedzenia nr 14 o dacie 2024-06-26: 1.58 sekundy

Koniec wypowiedzi. Odnotowano: 256 przemówień
Czas posiedzenia nr 14 o dacie 2024-06-27: 146.88 sekundy

Koniec wypowiedzi. Odnotowano: 96 przemówień
Czas posiedzenia nr 14 o dacie 2024-06-28: 57.33 sekundy

Koniec wypowiedzi. Odnotowano: 245 przemówień
Czas posiedzenia nr 15 o dacie 2024-07-11: 147.22 sekundy

Koniec wypowiedzi. Odnotowano: 143 przemówień
Czas posiedzenia nr 15 o dacie 2024-07-12: 84.30 sekundy

Koniec wypowiedzi. Odnotowano: 230 przemówień
Czas posiedzenia nr 16 o dacie 2024-07-23: 133.17 sekundy

Koniec wypowiedzi. Odnotowano: 256 przemówień
Czas posiedzenia nr 16 o dacie 2024-07-24: 144.73 sekundy

Koniec wypowiedzi. Odnotowano: 203 przemówień
Czas posiedzenia nr 16 o dacie 2024-07-25: 118.48 sekundy

Koniec wypowiedzi. Odnotowano: 160 przemówień
Czas posiedzenia nr 16 o dacie 2024-07-26: 93.64 sekundy

Koniec wypowiedzi. Odnotowano: 176 przemówień
Czas posiedzenia nr 17 o dacie 2024-09-11: 105.79 sekundy

Koniec wypowiedzi. Odnotowano: 228 przemówień
Czas posiedzenia nr 17 o dacie 2024-09-12: 134.29 sekundy

Koniec wypowiedzi. Odnotowano: 185 przemówień
Czas posiedzenia nr 17 o dacie 2024-09-13: 113.05 sekundy

Koniec wypowiedzi. Odnotowano: 211 przemówień
Czas posiedzenia nr 18 o dacie 2024-09-25: 122.97 sekundy

Koniec wypowiedzi. Odnotowano: 327 przemówień
Czas posiedzenia nr 18 o dacie 2024-09-26: 199.48 sekundy

Koniec wypowiedzi. Odnotowano: 171 przemówień
Czas posiedzenia nr 18 o dacie 2024-09-27: 100.41 sekundy

Koniec wypowiedzi. Odnotowano: 294 przemówień
Czas posiedzenia nr 18 o dacie 2024-10-01: 169.09 sekundy

Koniec wypowiedzi. Odnotowano: 152 przemówień
Czas posiedzenia nr 19 o dacie 2024-10-09: 90.62 sekundy

Koniec wypowiedzi. Odnotowano: 254 przemówień
Czas posiedzenia nr 19 o dacie 2024-10-10: 148.16 sekundy

Koniec wypowiedzi. Odnotowano: 177 przemówień
Czas posiedzenia nr 19 o dacie 2024-10-11: 103.19 sekundy

Koniec wypowiedzi. Odnotowano: 180 przemówień
Czas posiedzenia nr 20 o dacie 2024-10-16: 104.99 sekundy

Koniec wypowiedzi. Odnotowano: 279 przemówień
Czas posiedzenia nr 20 o dacie 2024-10-17: 189.19 sekundy

Koniec wypowiedzi. Odnotowano: 72 przemówień
Czas posiedzenia nr 20 o dacie 2024-10-18: 42.03 sekundy

Koniec wypowiedzi. Odnotowano: 234 przemówień
Czas posiedzenia nr 21 o dacie 2024-11-06: 142.01 sekundy

Koniec wypowiedzi. Odnotowano: 326 przemówień
Czas posiedzenia nr 21 o dacie 2024-11-07: 211.58 sekundy

Koniec wypowiedzi. Odnotowano: 271 przemówień
Czas posiedzenia nr 21 o dacie 2024-11-08: 182.36 sekundy

Koniec wypowiedzi. Odnotowano: 232 przemówień
Czas posiedzenia nr 22 o dacie 2024-11-19: 158.49 sekundy

Koniec wypowiedzi. Odnotowano: 349 przemówień
Czas posiedzenia nr 22 o dacie 2024-11-20: 228.77 sekundy

Koniec wypowiedzi. Odnotowano: 306 przemówień
Czas posiedzenia nr 22 o dacie 2024-11-21: 194.76 sekundy

Koniec wypowiedzi. Odnotowano: 196 przemówień
Czas posiedzenia nr 22 o dacie 2024-11-22: 117.23 sekundy

Koniec wypowiedzi. Odnotowano: 285 przemówień
Czas posiedzenia nr 22 o dacie 2024-11-27: 166.18 sekundy

Koniec wypowiedzi. Odnotowano: 262 przemówień
Czas posiedzenia nr 23 o dacie 2024-12-04: 135.41 sekundy

Koniec wypowiedzi. Odnotowano: 303 przemówień
Czas posiedzenia nr 23 o dacie 2024-12-05: 167.63 sekundy

Koniec wypowiedzi. Odnotowano: 72 przemówień
Czas posiedzenia nr 24 o dacie 2024-12-06: 43.03 sekundy

Koniec wypowiedzi. Odnotowano: 188 przemówień
Czas posiedzenia nr 25 o dacie 2024-12-18: 129.17 sekundy

Koniec wypowiedzi. Odnotowano: 250 przemówień
Czas posiedzenia nr 25 o dacie 2024-12-19: 139.01 sekundy

Koniec wypowiedzi. Odnotowano: 83 przemówień
Czas posiedzenia nr 25 o dacie 2024-12-20: 48.72 sekundy

Koniec wypowiedzi. Odnotowano: 279 przemówień
Czas posiedzenia nr 26 o dacie 2025-01-08: 157.17 sekundy

Koniec wypowiedzi. Odnotowano: 246 przemówień
Czas posiedzenia nr 26 o dacie 2025-01-09: 150.50 sekundy

Koniec wypowiedzi. Odnotowano: 108 przemówień
Czas posiedzenia nr 26 o dacie 2025-01-10: 62.17 sekundy

Koniec wypowiedzi. Odnotowano: 225 przemówień
Czas posiedzenia nr 27 o dacie 2025-01-22: 123.10 sekundy

Koniec wypowiedzi. Odnotowano: 266 przemówień
Czas posiedzenia nr 27 o dacie 2025-01-23: 158.57 sekundy

Koniec wypowiedzi. Odnotowano: 133 przemówień
Czas posiedzenia nr 27 o dacie 2025-01-24: 80.58 sekundy

## Sprawdzenie różnych informacji o politicians_df. Poprawność dataframe'a, kształt, przykład.
## Zapisanie dataframe'a do excela w formacie .xlsx

In [5]:
politicians_df.iloc[0,0]

'Prezydent Rzeczypospolitej Polskiej Andrzej Duda'

In [6]:
politicians_df.sample().iloc[0,1]

'Szanowna Pani Marszałek! Szanowna Izbo! Zanim zostałem posłem, byłem radnym \r\nmiasta Częstochowy. To jest pierwsze miasto w Polsce, które wprowadziło in \r\nvitro w 2012 r. W 2015 r. był taki moment, że radni Częstochowy chcieli \r\nzaktualizować ten program, zwiększyć kwotę przyznawaną parom i klub Lewicy i \r\nPlatformy był za, a klub PiS-u był przeciw.W 2015 r. to głosy naszego częstochowskiego klubu, klubu mieszkańców \r\nCzęstochowy, zdecydowały o tym, że do tej pory w Częstochowie funkcjonuje in \r\nvitro i urodziło się 77 dzieci.Cieszę się, że historia zatacza koło, bo wtedy w Częstochowie mieliśmy duży \r\ndylemat przez to, że mieszkańcy, osoby zameldowane w Częstochowie mogą \r\nkorzystać z tego programu, a mieszkańcy sąsiednich gmin (Dzwonek) jak \r\nBlachownia, Koniecpol czy Lubliniec - nie. Cieszę się, że mogę to dzisiaj \r\nnaprawić i razem z państwem zagłosować za in vitro. Dziękuję bardzo. \r\n(Oklaski)'

In [8]:
politicians_df.shape

(15878, 4)

In [9]:
politicians_df.groupby('politician').size().sort_values(ascending=False)

politician
Poseł Witold Tumanowicz                                                                                                       360
Poseł Jarosław Sachajko                                                                                                       322
Poseł Zbigniew Bogucki                                                                                                        205
Poseł Tadeusz Tomaszewski                                                                                                     199
Poseł Grzegorz Braun                                                                                                          182
                                                                                                                             ...
Poseł Zbigniew Chmielowiec (tekst niewygłoszony)                                                                                1
Poseł Sprawozdawca Alicja Chybicka                                                                                              1
Poseł Sprawozdawca Aleksandra Kot                                                                                               1
Poseł Sprawozdawca Agnieszka Maria Kłopotek                                                                                     1
Członek Państwowej Komisji do spraw Przeciwdziałania Wykorzystaniu Seksualnemu Małoletnich Poniżej Lat 15 Joanna Napierała      1
Length: 864, dtype: int64

In [11]:
politicians_df.to_excel('politycy.xlsx', index=False)

## Załadowanie datasetu z wypowiedziami polityków. Załadowanie modelu. Deklaracja funkcji embedding'u i porównywania.

In [3]:
dataset_politycy = pd.read_csv('politycy.csv', encoding='utf-8', sep=';')
dataset_politycy = dataset_politycy.dropna(subset=["utterance", "politician", "sejm_session", "date"])

In [4]:
dataset_politycy['utterance'] = dataset_politycy['utterance'].str.replace(r'[\n\r]', '', regex=True)

In [5]:
dataset_politycy.iloc[7543,1]

'Dziękuję.Pani Marszałek! Szanowni Państwo! Wysoka Izbo! Myślę, że do tego wszystkiego, co powiedział przed chwilą pan poseł Marek Suski, trudno coś jeszcze dodać, ale warto wspomnieć o obecnych obchodach. Prawda jest taka, że dzisiaj staramy się pamiętać o tym, co stanowi podstawę tego, że żyjemy w wolnej Polsce.Szanowni państwo, chciałabym dzisiaj tutaj, z tego miejsca zacytować list pana przewodniczącego Piotra Dudy, list, który został skierowany do uczestników obchodów 48. rocznicy wydarzeń czerwcowych: ˝Solidarność˝ nie powstała z próżni. Fundamenty pod jej budowę położyli strajkujący w czerwcu 1956 r. w Poznaniu robotnicy, kładli je uczestnicy wydarzeń Grudnia 1970 r., wreszcie położyli je pracownicy, którzy odważyli się wystąpić przeciwko władzy w czerwcu 1976 r. Ówczesne wydarzenia w Radomiu, Płocku, Ursusie, ale i w wielu innych miejscach w Polsce, to także nasze dziedzictwo, o którym nie wolno nam zapomnieć. To bardzo ważne.Przewodniczący mówił o krzyżu: Krzyż zawsze nam towarzyszył. Nieraz musieliśmy go bronić. Dziś stajemy przed takim samym wyzwaniem. Krzyż stał się niewygodny dla władzy. Znów zdejmuje się go ze ścian urzędów i budynków użyteczności publicznej. Władza znów boi się krzyża, bo wie, jak wielką ma on moc. A my znów musimy stanąć w jego obronie - zaznaczył przewodniczący Piotr Duda. To bardzo ważne, bo krzyż symbolizuje nasze ideały. Wartości chrześcijańskie i nauka społeczna Kościoła to nasz testament, wpisany w statut związku. Nie zrezygnujemy z nich, pamiętając, jak wielkie zobowiązanie mamy do wypełnienia. W 1976 r. robotnicy Ursusa i Radomia walczyli o godność, o podmiotowe traktowanie, o to, by władza przestała narzucać nam swoją wolę. Dziś walczymy o to samo. W obliczu agresywnej polityki klimatycznej, jaką narzuca nam Unia Europejska, stajemy do walki o podstawowe prawa, o to, by móc skorzystać z najwyższej formy demokracji, o którą jako ˝Solidarność˝ sami walczyliśmy. (Dzwonek) Za wzór bierzemy wszystkich tych, którzy przyczynili się do wyzwolenia Polski z rąk władzy autorytarnej. Dlatego dziś oddajemy hołd bohaterom Czerwca 1976 r. Bez was nie byłoby ani wolnej Polski, ani ˝Solidarności˝. Jesteśmy wam winni dozgonny szacunek i pamięć. I warto o tym pamiętać. Dziękuję. (Oklaski)'

In [8]:
import re

def split_and_filter(row):
    sentences = re.split(r'(?<=[.!?])\s+', row['utterance'])
    filtered_sentences = [s for s in sentences if len(s.split()) >= 10]
    return pd.DataFrame({'politician': row['politician'], 'utterance': filtered_sentences})

dataset_filtered_politycy = pd.concat(dataset_politycy.apply(split_and_filter, axis=1).tolist(), ignore_index=True)

print(dataset_filtered_politycy)
dataset_filtered_politycy.to_excel('politycy_filtered.xlsx', index=False)

                                              politician  \
0       Prezydent Rzeczypospolitej Polskiej Andrzej Duda
1       Prezydent Rzeczypospolitej Polskiej Andrzej Duda
2       Prezydent Rzeczypospolitej Polskiej Andrzej Duda
3       Prezydent Rzeczypospolitej Polskiej Andrzej Duda
4       Prezydent Rzeczypospolitej Polskiej Andrzej Duda
...                                                  ...
170841        Poseł Andrzej Szejna (tekst niewygłoszony)
170842        Poseł Andrzej Szejna (tekst niewygłoszony)
170843        Poseł Andrzej Szejna (tekst niewygłoszony)
170844        Poseł Andrzej Szejna (tekst niewygłoszony)
170845        Poseł Andrzej Szejna (tekst niewygłoszony)

                                                utterance
0       Szanowne Panie Posłanki i Szanowni Panowie Pos...
1       Dziękuję, dziękuję i jeszcze raz dziękuję wszy...
2       Oczywiście my, Polacy, w wielu sprawach istotn...
3       Prowadzimy często gorące spory i zapewne będzi...
4       Najważniejsze jednak jest to, że spory te rozs...
...                                                   ...
170841  To wyzwanie wymaga zdecydowanych działań i wsp...
170842  Wykorzystajmy ten czas, aby zbudować silniejsz...
170843  Niniejszym oświadczam, że w wyniku pomyłki zag...
170844  porządku dziennego: Pierwsze czytanie rządoweg...
170845  Było to głosowanie nad skierowaniem projektu u...

[170846 rows x 2 columns]

In [4]:
dataset_filtered_politycy = pd.read_csv('politycy_filtered.csv', encoding='utf-8', sep=';')
dataset_filtered_politycy = dataset_filtered_politycy.dropna(subset=["politician", "utterance"])

# Model AI

In [3]:
#model = SentenceTransformer('all-MiniLM-L6-v2')
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

In [41]:
# Funkcja do konwersji tekstu na wektor (embedding)
def get_embedding(text):
    return model.encode(text)

def get_similarity(user_input, df_embeddings):
    # Wektor wypowiedzi użytkownika
    user_embedding = get_embedding(user_input)
    
    # Oblicz podobieństwo z każdą wypowiedzią w dataset
    similarities = []
    for index, row in df_embeddings.iterrows():
        politician_embedding = np.array(row['embedding'])
        
        similarity = cosine_similarity([user_embedding], [politician_embedding])[0][0]
        similarities.append((similarity, row['politician'], row['utterance']))

    # Posortuj podobieństwa
    similarities.sort(reverse=True, key=lambda x: x[0])
    
    top_n = 4  # Weź 4 najbliższe wypowiedzi
    avg_similarity = np.mean([sim for sim, _, _ in similarities[:top_n]])
    
    return avg_similarity, similarities[:top_n]

## Konwersja dataframe'u z wypowiedziami (podzielonymi na zdania i przefiltrowanymi) na embeddings

In [6]:
pip install tqdm

Requirement already satisfied: tqdm in c:\users\mojke\anaconda3\lib\site-packages (4.65.0)
Requirement already satisfied: colorama in c:\users\mojke\anaconda3\lib\site-packages (from tqdm) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [7]:
from tqdm import tqdm

politycy_phrases_embeddings = [
    (get_embedding(row["utterance"]), row["politician"], row["utterance"]) 
    for _, row in tqdm(dataset_filtered_politycy.iterrows(), total=len(dataset_filtered_politycy))
]

100%|██████████| 170846/170846 [54:28<00:00, 52.27it/s]

In [28]:
df_politycy_phrases_embeddings = pd.DataFrame(politycy_phrases_embeddings, columns=["embedding", "politician", "utterance"])
print(df_politycy_phrases_embeddings.shape)

(170846, 3)

In [ ]:
df_politycy_phrases_embeddings.to_excel('df_politycy_phrases_embeddings.xlsx', index=False)

In [ ]:
df_politycy_phrases_embeddings = pd.read_csv("df_politycy_phrases_embeddings.csv", encoding="utf-8", sep=';')

df_politycy_phrases_embeddings["embedding"] = df_politycy_phrases_embeddings["embedding"].apply(
    lambda x: np.array(list(map(float, x.strip("[]").split())))
)

df_politycy_phrases_embeddings["embedding"] = df_politycy_phrases_embeddings["embedding"].apply(lambda x: np.array(list(map(float, x.split(',')))))

In [30]:
data = []
for embedding, politician, utterance in politycy_phrases_embeddings:
    data.append({
        "embedding": ','.join(map(str, embedding)),  # Zapis embeddingu jako string
        "politician": politician,
        "utterance": utterance
    })

df_embeddings = pd.DataFrame(data)

df_embeddings.to_excel('politycy_embeddings.xlsx', index=False)
print("Zapisano embeddingi do pliku politycy_embeddings.xlsx!")

Zapisano embeddingi do pliku politycy_embeddings.xlsx!

In [31]:
df_embeddings = pd.read_csv("politycy_embeddings.csv", encoding="utf-8", sep=';')
df_embeddings["embedding"] = df_embeddings["embedding"].apply(lambda x: np.array(list(map(float, x.split(',')))))

In [33]:
print(f"Liczba wierszy: {len(df_embeddings)}")
print(f"Kształt DataFrame: {df_embeddings.shape}")
display(df_embeddings.iloc[0:5,:])  # Wyświetlenie pierwszej krotki

Liczba wierszy: 170846
Kształt DataFrame: (170846, 3)

,embedding,politician,utterance
0,"[-0.08385016, 0.34024933, 0.052966405, -0.2829...",Prezydent Rzeczypospolitej Polskiej Andrzej Duda,Szanowne Panie Posłanki i Szanowni Panowie Pos...
1,"[0.06613045, 0.33783805, 0.32265288, 0.0248571...",Prezydent Rzeczypospolitej Polskiej Andrzej Duda,"Dziękuję, dziękuję i jeszcze raz dziękuję wszy..."
2,"[-0.01098743, 0.08707601, -0.07281946, 0.14722...",Prezydent Rzeczypospolitej Polskiej Andrzej Duda,"Oczywiście my, Polacy, w wielu sprawach istotn..."
3,"[0.08836559, 0.13197224, -0.27648735, 0.072173...",Prezydent Rzeczypospolitej Polskiej Andrzej Duda,Prowadzimy często gorące spory i zapewne będzi...
4,"[-0.13960795, 0.21945687, -0.30796283, -0.1908...",Prezydent Rzeczypospolitej Polskiej Andrzej Duda,"Najważniejsze jednak jest to, że spory te rozs..."

In [34]:
df_embeddings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170846 entries, 0 to 170845
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   embedding   170846 non-null  object
 1   politician  170846 non-null  object
 2   utterance   170846 non-null  object
dtypes: object(3)
memory usage: 3.9+ MB

In [35]:
df_embeddings.sample()

,embedding,politician,utterance
53874,"[-0.006533415, 0.34816638, -0.008759589, -0.14...",Poseł Marek Suski,(Oklaski)Wicemarszałek Włodzimierz Czarzasty:D...

In [48]:
user_input = "Zielona energia jest bardzo istotna i powinniśmy skupić się na rozwoju rozwiązaniach ekologicznych. Musimy redukować energię węglową i zastapić ją energią z wiatru czy z wody."
#user_input = "Polacy potrzebują legalnej aborcji, ponieważ to jest prawo kobiety i nie można przymuszać kobiet."
#user_input = "Aborcja to zabójstwo dziecka i nie można tego zalegalizować. Jest to sprzeczne z jakimikolwiek prawami moralnymi i religijnymi"
#user_input = "Aborcja powinna być dozwolona w przypadku gwaltu, ciężkiej choroby dziecka lub możliwej śmierci matki. Ale nigdy nie dozwolona na życzenie."
#user_input = "Prawo do posiadania broni powinno być dozwolone dla przeciętnego obywatela. Ludzie muszą mieć możliwość obrony wlasnej."

avg_similarity, top_similarities = get_similarity(user_input, df_embeddings)

print(user_input)
print(f"Średnie podobieństwo: {avg_similarity}")
for similarity, politician, utterance in top_similarities:
    print(f"Polityk: {politician}, Wypowiedź: {utterance}, Podobieństwo: {similarity} \n")

Zielona energia jest bardzo istotna i powinniśmy skupić się na rozwoju rozwiązaniach ekologicznych. Musimy redukować energię węglową i zastapić ją energią z wiatru czy z wody.
Średnie podobieństwo: 0.7564250766106172
Polityk: Poseł Małgorzata Pępek, Wypowiedź: Ale wszyscy wiemy, że zielona energia potrzebuje przede wszystkim stabilności regulacyjnej., Podobieństwo: 0.7627143439478747

Polityk: Poseł Tomasz Piotr Nowak, Wypowiedź: Otwieramy się na transformację energetyczną, otwieramy się na zieloną energię, ale także myślimy o stabilizacji systemu energetycznego, bo wiemy doskonale, że ta stabilizacja też musi być., Podobieństwo: 0.7616027379440568

Polityk: Poseł Bożena Lisowska, Wypowiedź: Potrzeba nam strategii budowania większego potencjału zielonej energii i inwestycji w OZE, w rozwój technologii niskoemisyjnych, w tym technologii wodorowych, które pomogą nam uzyskać autonomię energetyczną., Podobieństwo: 0.7582319389522687

Polityk: Poseł Urszula Pasławska, Wypowiedź: Przyspieszy to odchodzenie od węgla na rzecz czystej, zielonej energii., Podobieństwo: 0.7431512855982686